### ISSUE TITLE
minimizing the "feed setting" tab makes all other tabs unresponsive

### ISSUE THREAD

**Issue by Kepler-16b** [todhm/sd_feed#3]
### Baseic info
**Browser**: Microsoft Edge Dev (version 113.0.1774.7)
**Environment**: python: 3.10.7  •  torch: 2.0.0+cu118  •  xformers: 0.0.17rc482  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
**Arguments for launching webui**: --theme dark --port 7870 --xformers --autolaunch --api --upcast-sampling --disable-nan-check --administrator

### Issue
1. Upon launch, webui always show a blank feed (see [screenshot](https://imgur.com/gallery/wyvauzv)), freeze for about couple seconds before going into the normal interface.
2. Clicking the "feed setting" tab (to minimize it) will make all other tabs unresponsive. Can only be fixed by reloading webui.

### Possible way to reproduce
Try the latest commit [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81), and simply close the "feed setting" tab under image window.

**Comment by todhm** [comment]
we change design to fix this issue thanks for reporting
