### ISSUE TITLE
didn't see feeds from other people

### ISSUE THREAD

**Issue by bluelovers** [todhm/sd_feed#5]
![image](https://user-images.githubusercontent.com/167966/231928525-ed86ce3f-90c0-4d2a-a859-36be86a832e1.png)

**Comment by todhm** [comment]
What's your os system how did you learn this system?
Could u please turn on and off terminal and restart program?

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/231943519-bd6eedc6-2ce3-4113-b0a1-2b3324d26479.png)

**Comment by sakada3** [comment]
it`s happens to me either.
can you send DM via discord?
Nebula#7553

**Comment by todhm** [comment]
I send you friend request

**Comment by todhm** [comment]
I just deployed new version but I can't check this issue since I didn't meet this error before. 
Could you please check  whether or not it works now?

**Comment by bluelovers** [comment]
maybe because `https`

**Comment by todhm** [comment]
Actually it works when I access through ngrok

**Comment by jemmywong79** [comment]
Got it fix. I need latest Gradio 3.23. Mine was Gradio 3.16 so it didn't work. Add a "Git pull" inside webui-user.bat on the first line. After update remember to close it back by adding "@" in front. Finger cross hope others extension does not crush on this new Gradio.

**Comment by Anathaema** [comment]
I get the same problem
![2](https://user-images.githubusercontent.com/131543028/233794273-375361f1-2cde-43d4-a1d9-0e7fff21e295.png)

My gradio is 3.23 as can be seen at the bottom.

**Comment by sauravsinghb** [comment]
![firefox_Qg5ow1VdtD](https://user-images.githubusercontent.com/61663583/233877531-19cc50a9-b42c-46f8-bc13-1936496c1596.jpg)
this issue is happening in https://github.com/vladmandic/automatic

**Comment by sauravsinghb** [comment]
i just find out that system info extension causing this issue 
turn off system info extension

**Comment by todhm** [comment]
Sorry for late update I resolved issue with conflicts.
