### ISSUE TITLE
What is this plugin, exactly?

### ISSUE THREAD

**Issue by SoftwareGuy** [todhm/sd_feed#6]
Hi there! :wave: 

I have a few questions.

Firstly, what exactly does this plugin do? The description that you've provided in the readme (since you didn't add a description into the github repository field) is rather... confusing. It's a "custom extension", but doesn't explain what it is. Sure, one can upload artwork to the feed, but for what purpose? Is just a image gallery plugin for the Web UI so people can get inspiration or check out other generated art?

Looking at the plugin source, it seems you're basically processing a JSON feed of data from a remote server, although I hope this is secure enough to avoid being compromised and have malicious contents injected into a user's WebUI instance. Or even worse, have it replace files in users' filesystem with malicious files.

Finally, when you say "uploaded image might be exposed to our promotion contents", please elaborate on the "promotion" part. Are you trying to make a profit off other people's AI generated art pieces? How is the "sponsorship" feature going to work? Are you going to take a cut of the sponsorship money a user receives or what?

I feel this needs to be clarified, otherwise people may view the plugin as suspicious.

**Comment by todhm** [comment]
Thanks for your question. 
1. We are growing WEBUI community where you can get fame and reputation. You also can get feedback on others' jobs. 
2.We do not manipulate users' content we only use our own files. Also restrict file can be uploaded to server.
3.  It means that there is the possibility that users' content might be exposed to outer sources indirectly when we try to introduce our extension in outer sources. 
Hope that my answers resolve your questions.

**Comment by todhm** [comment]
I will close this issue. If you have any questions please ask Thanks.
